# Generated by Django 3.0.3 on 2020-02-06 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_contents',
            new_name='comment_content',
        ),
    ]
