# Generated by Django 3.0.3 on 2020-02-20 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_delete_comment'),
        ('post', '0002_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
